import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:podium/src/login/login.dart';

class CountryCodeDropdown extends StatefulWidget {
  const CountryCodeDropdown({super.key});

  @override
  CountryCodeDropdownState createState() => CountryCodeDropdownState();
}

class CountryCodeDropdownState extends State<CountryCodeDropdown> {
  String selectedCountryCode = 'United States (+1)';
  List<String> countryCodes = [
    'United States (+1)',
    'Canada (+1)',
    'Mexico (+52)',
    'United Kingdom (+44)',
    'Afghanistan (+93)',
    'Aland Islands (+358)',
    'Albania (+355)',
    'Algeria (+213)',
    'American Samoa(+1)',
    'Andora (+376)',
    'Angola (+244)',
    'Anguilla (+1)',
    'Antigua & Barbuda (+1)',
    'Argentina (+54)',
    'Armenina (+374)',
    'Aruba (+297)',
    'Australia (+61)',
    'Austria (+43)',
    'Azerbaijan (+994)',
    'Bahamas (+1)',
    'Bahrain (+973)',
    'Bangladesh (+880)',
    'Barbados (+1)',
    'Belarus (+375)',
    'Belgium (+32)',
    'Belize (+501)',
    'Benin (+229)',
    'Bermuda (+1)',
    'Bhutan (+975)',
    'Bolivia (+591)',
    'Bonaire, Sint Eustatius and Saba (+599)',
    'Bosnia & Herzegovina (+387)',
    'Botswana (+267)',
    'Brazil (+55)',
    'British Indian Ocean Territory (+246)',
    'British Virgin Islands (+1)',
    'Brunei (+673)',
    'Bulgaria (+359)',
    'Burkina Faso (+226)',
    'Burundi (+257)',
    'Cambodia (+855)',
    'Cameroon (+237)',
    'Cape Verde (+238)',
    'Cayman Islands (+1)',
    'Central African Republic (+236)',
    'Chad (+235)',
    'Chile (+56)',
    'China (+86)',
    'Christmas Island (+61)',
    'Cocos (Keeling) Islands (+61)',
    'Colombia (+57)',
    'Comoros (+269)',
    'Congo (+242)',
    'Cook Islands (+242)',
    'Costa Rica (+506)',
    "C'ote d'Ivoire (+225)",
    'Croatia (+225)',
    'Cuba (+53)',
    'Curacao (+599)',
    'Cyprus (+357)',
    'Czechia (+420)',
    'Democratic Republic of the Congo (+243)',
    'Denmark (+45)',
    'Djibouti (+253)',
    'Dominica (+1)',
    'Dominican Republic (+1)',
    'Ecuador (+593)',
    'Egypt (+20)',
    'El Salvador (+503)',
    'Equatorial Guinea (+240)',
    'Eritrea (+291)',
    'Estonia (+372)',
    'Eswatini (+268)',
    'Ethiopia (+251)',
    'Falkland Islands (Islas Malvinas) (+500)',
    'Faroe Islands (+298)',
    'Fiji (+679)',
    'Finland (+358)',
    'France (+33)',
    'French Guinea (+594)',
    'French Polynesia (+689)',
    'Gabon (+241)',
    'Gambia (+220)',
    'Georgia (+995)',
    'Germany (+49)',
    'Ghana (+233)',
    'Gibraltar (+350)',
    'Greece (+30)',
    'Greenland (+299)',
    'Grenada (+1)',
    'Guadeloupe (+590)',
    'Guam (+1)',
    'Guatemala (+502)',
    'Guernsey (+44)',
    'Guinea (+224)',
    'Guinea-Bissau (+245)',
    'Guyana (+592)',
    'Haiti (+509)',
    'Honduras (+504)',
    'Hong Kong (+852)',
    'Hungary (+36)',
    'India (+91)',
    'Indonesia (+62)',
    'Iraq (+964)',
    'Ireland (+353)',
    'Isle of Man (+44)',
    'Israel (+972)',
    'Italy (+39)',
    'Jamaica (+1)',
    'Japan (+81)',
    'Jersey (+44)',
    'Jordan (+962)',
    'Kazakhstan (+7)',
    'Kenya (+254)',
    'Kiribati (+686)',
    'Kosovo (+383)',
    'Kuwait (+965)',
    'Kyrgyzstan (+996)',
    'Laos (+856)',
    'Lebanon (+961)',
    'Lesotho (+266)',
    'Liberia (+231)',
    'Libya (+218)',
    'Liechtenstien (+423)',
    'Lithuania (+370)',
    'Luxembourg (+352)',
    'Macau (+853)',
    'North Macedonia (+389)',
    'Malawi (+265)',
    'Malaysia (+60)',
    'Maldives (+960)',
    'Mali (+223)',
    'Malta (+356)',
    'Marshall Islands (+692)',
    'Martinique (+596)',
    'Mauritania (+222)',
    'Mauritius (+230)',
    'Mayotte (+262)',
    'Micronesia (+691)',
    'Moldova (+373)',
    'Monaco (+212)',
    'Mongolia (+976)',
    'Montenegro (+382)',
    'Montserrat (+1)',
    'Morocco (+212)',
    'Mozambique (+258)',
    'Myanmar (+95)',
    'Namibia (+264)',
    'Nauru (+264)',
    'Namibia (+264)',
    'Nepal (+977)',
    'Netherlands (+31)',
    'New Caledonia (+64)',
    'New Zealand (+64)',
    'Nicaragua (+234)',
    'Niger (+227)',
    'Nigeria (+234)',
    'Niue (+683)',
    'Norfolk Island (+672)',
    'Northern Mariana Islands (+1)',
    'Norway (+47)',
    'Oman (+968)',
    'Pakistan (+92)',
    'Palau (+92)',
    'Palestinian Territories (+970)',
    'Panama (+507)',
    'Papau New Guinea (+675)',
    'Paraguay (+595)',
    'Peru (+51)',
    'Phillipines (+63)',
    'Pitcairn Island (+64)',
    'Poland (+48)',
    'Portugal (+351)',
    'Puerto Rico (+1)',
    'Qatar (+974)',
    'Reunion (+262)',
    'Romania (+40)',
    'Russia (+7)',
    'Rwanda (+250)',
    'Samoa (+685)',
    'San Marino (+378)',
    'Sao Tome & Principe (+239)',
    'Saudi Arabia (+966)',
    'Senegal (+221)',
    'Serbia (+381)',
    'Seychelles (+248)',
    'Sierra Leone (+65)',
    'Singapore (+65)',
    'Sint Maarten (+1)',
    'Slovakia (+421)',
    'Slovenia (+386)',
    'Solomon Islands (+677)',
    'Somalia (+252)',
    'South Africa (+27)',
    'South Georgia & South Sandwich Islands (+500)',
    'South Korea (+82)',
    'South Sudan (+211)',
    'Spain (+34)',
    'Sri Lanka (+94)',
    'St. Barthelemy (+590)',
    'St. Helena (+290)',
    'St. Kitts & Nevis (+1)',
    'St. Lucia (+1)',
    'St. Martin(+590)',
    'St. Pierre & Miquelon (+508)',
    'St. Vincent & Grenadines (+1)',
    'Sudan (+249)',
    'Suriname (+597)',
    'Svalberd & Jan Mayen (+47)',
    'Sweden (+46)',
    'Switzerland (+41)',
    'Taiwan (+886)',
    'Tajikistan (+992)',
    'Tanzania (+255)',
    'Thailand (+66)',
    'Timor-Leste (+670)',
    'Togo (+228)',
    'Tokelau (+690)',
    'Tonga (+676)',
    'Trinidad & Tobago (+1)',
    'Tunisia (+216)',
    'Turkey (+90)',
    'Turkmenistan (+993)',
    'Turks & Caicos Islands (+1)',
    'Tuvalu (+688)',
    'U.S. Virgin Islands (+1)',
    'Uganda (+256)',
    'Ukraine (+380)',
    'United Arab Emirates (+971)',
    'Uruguay (+598)',
    'Uzbekistan (+998)',
    'Vanuatu (+678)',
    'Vatican City (+379)',
    'Venezuela (+58)',
    'Vietnam (+84)',
    'Wallis & Futuna (+681)',
    'Western Sahara (+212)',
    'Yemem (+967)',
    'Zambia (+260)',
    'Zimbabwe (+263)',
  ];
  @override
  Widget build(BuildContext context) {
    return DropdownButtonFormField<String>(
      dropdownColor: Colors.white,
      value: selectedCountryCode,
      icon: const Icon(Icons.arrow_drop_down),
      decoration: InputDecoration(
        labelText: 'Country/Region',
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
        ),
      ),
      onChanged: (String? newValue) {
        debugPrint(
            "newValue!.split('(')[1].split(')')[0]: ${newValue!.split('(')[1].split(')')[0]}");
        context
            .read<LoginCubit>()
            .countryCodeChanged(newValue!.split('(')[1].split(')')[0]);
        setState(() {
          selectedCountryCode = newValue;
        });
      },
      items: countryCodes.map<DropdownMenuItem<String>>((String value) {
        return DropdownMenuItem<String>(
          value: value,
          child: Text(value),
        );
      }).toList(),
    );
  }
}
